name: Reusable CD - Deploy to Production

on:
  workflow_call:
    # Định nghĩa các secrets sẽ được nhận từ workflow gọi nó
    secrets:
      DB_URL:
        required: true
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      SERVER_PORT:
        required: true
      JWT_SECRET:
        required: true
      JWT_EXPIRATION:
        required: true
      SPRING_MAIL_HOST:
        required: true
      SPRING_MAIL_PORT:
        required: true
      SPRING_MAIL_USERNAME:
        required: true
      SPRING_MAIL_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          path: '/home/github/Danang-Culinary-Atlas'

      - name: Verify files in working directory
        run: |
          ls -la
          echo "Working directory verified successfully."

      - name: Create .env file from secrets
        working-directory: '/home/github/Danang-Culinary-Atlas'
        run: |
          echo "Creating .env file..."
          cat << EOF > .env
          DB_URL=${{ secrets.DB_URL }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          SERVER_PORT=${{ secrets.SERVER_PORT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
          SPRING_MAIL_HOST=${{ secrets.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT=${{ secrets.SPRING_MAIL_PORT }}
          SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}
          EOF
          echo ".env file created successfully."

      - name: Stop old containers and start new ones
        working-directory: '/home/github/Danang-Culinary-Atlas'
        run: docker-compose up --build -d

      - name: Clean up old docker images
        working-directory: '/home/github/Danang-Culinary-Atlas'
        run: docker image prune -f